### ISSUE TITLE
mvn clean install - Failed

### ISSUE THREAD

**Issue by DigitLib** [dbmdz/cudami#1148]
Installed Ubuntu 20.04 LTS server in VM to test cudami.
Java version openjdk-11.0.11
Maven version 3.6.3

Downloaded v5.0.1
Followed steps from readme
cd cudami-5.0.1
enter mvn clean install 
get this
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 14 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 14 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] DigitalCollections: cudami                                         [pom]
[INFO] DigitalCollections: cudami Repository Client                       [jar]
[INFO] DigitalCollections: cudami Management Webapp                       [jar]
[INFO] DigitalCollections: cudami Repository Server                       [pom]
[INFO] DigitalCollections: cudami Repository Server (Backend API)         [jar]
[INFO] DigitalCollections: cudami Repository Server (Backend IMPL File)   [jar]
[INFO] DigitalCollections: cudami Repository Server (Backend IMPL InMemory) [jar]
[INFO] DigitalCollections: cudami Repository Server (Backend IMPL JDBI PostgreSql) [jar]
[INFO] DigitalCollections: cudami lobid.org Client                        [jar]
[INFO] DigitalCollections: cudami Repository Server (Backend IMPL External System lobid.org) [jar]
[INFO] DigitalCollections: cudami Repository Server (Business)            [jar]
[INFO] DigitalCollections: cudami Repository Server (Webapp)              [jar]
[INFO] DigitalCollections: cudami Templates                               [pom]
[INFO] DigitalCollections: cudami Templates (Website Spring Boot)         [jar]
[INFO] 
[INFO] ---------------< de.digitalcollections.cudami:dc-cudami >---------------
[INFO] Building DigitalCollections: cudami 5.0.1                         [1/14]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ dc-cudami ---
[INFO] 
[INFO] --- githook-maven-plugin:1.0.5:install (default) @ dc-cudami ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for DigitalCollections: cudami 5.0.1:
[INFO] 
[INFO] DigitalCollections: cudami ......................... FAILURE [  0.263 s]
[INFO] DigitalCollections: cudami Repository Client ....... SKIPPED
[INFO] DigitalCollections: cudami Management Webapp ....... SKIPPED
[INFO] DigitalCollections: cudami Repository Server ....... SKIPPED
[INFO] DigitalCollections: cudami Repository Server (Backend API) SKIPPED
[INFO] DigitalCollections: cudami Repository Server (Backend IMPL File) SKIPPED
[INFO] DigitalCollections: cudami Repository Server (Backend IMPL InMemory) SKIPPED
[INFO] DigitalCollections: cudami Repository Server (Backend IMPL JDBI PostgreSql) SKIPPED
[INFO] DigitalCollections: cudami lobid.org Client ........ SKIPPED
[INFO] DigitalCollections: cudami Repository Server (Backend IMPL External System lobid.org) SKIPPED
[INFO] DigitalCollections: cudami Repository Server (Business) SKIPPED
[INFO] DigitalCollections: cudami Repository Server (Webapp) SKIPPED
[INFO] DigitalCollections: cudami Templates ............... SKIPPED
[INFO] DigitalCollections: cudami Templates (Website Spring Boot) SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.850 s
[INFO] Finished at: 2021-08-06T13:24:21Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.github.phillipuniverse:githook-maven-plugin:1.0.5:install (default) on project dc-cudami: Not a git repository, could not find a .git/hooks directory anywhere in the hierarchy of /home/andrac/cudami/target. Turn off this behavior with skipRepositoryCheck=false -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

There are no /target dir created

**Comment by morpheus-87** [comment]
Thank you very much for your issue, @DigitLib ! Sorry, that you had to wait so long for an answer :see_no_evil: did you clone the repository with `git`? Or did you just download it from the releases?
