### ISSUE TITLE
Review JSONB indexing

### ISSUE THREAD

**Issue by clorenz** [dbmdz/cudami#2093]
Currrently, we use different approaches to enable indexing of JSON fiels and composite data, e.g. splitting content into an own indexed field, or using functions to fill a composite data type (see `ManifestationRepositoryImpl`).

This should be reviewed, to see, if more recent PostgreSQL versions can provided a better/direct approach.

Literature:
- https://scalegrid.io/blog/using-jsonb-in-postgresql-how-to-effectively-store-index-json-data-in-postgresql/

**Comment by daforster** [comment]
No news so far but it's always on radar.
