### ISSUE TITLE
Add Render Web Page Method to Cudami Client API

### ISSUE THREAD

**Issue by christian-bsb** [dbmdz/cudami#975]
The Cudami Client supports webpage rendering but not with a API but by its internal thymeleaf templates.
The function shoud be provided by the API of the client instead.

e.g.
String renderWebPage(WebPage) 

the App takes the String and strores it in the model. In the rendering process the model attribute could be included in the 
rendered response with the thymeleaf utext type.

**Comment by morpheus-87** [comment]
This functionality will not be implemented.
